In [2]:
import numpy as np
mat = [x+1 for x in range(9)]

In [5]:
mat = np.reshape(mat,(3,3))
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
mat2 = [1 for x in range(9)]
mat2 = np.reshape(mat2,(3,3))
mat2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
np.multiply(mat,mat2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1]:
x1 = [1,1]
x2 = [2,2]

In [3]:
import numpy as np
np.dot(x1,x2)

4

In [4]:
np.dot(x1,x1)

2

In [6]:
np.dot(x1,x2)

4

In [7]:
np.dot(x2,x1)

4

In [8]:
np.dot(x2,x2)

8

In [9]:
a = [1,2,3]
b = [4,5,6]

In [10]:
np.dot(a,b)

32

In [11]:
np.dot(b,a)

32

In [12]:
w = [1,1]

In [13]:
np.dot(w,x1)

2

In [14]:
np.dot(w,x2)

4