### 사칙연산

### 자료형

#### 문자열과 수치를 함께 표시

In [1]:
x = 1/3
print('x= '+str(x))

x= 0.3333333333333333


In [2]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


In [3]:
x = 1/3
y = 1.7
z = 1/4

print("weight: {0}kg {1}kg {2}kg".format(x,y,z))

weight: 0.3333333333333333kg 1.7kg 0.25kg


In [4]:
#소수점 이하 n자리까지
print('weight: {0:.2f}kg, y = {1:.2f}kg, z ={2:.2f}kg'.format(x,y,z))

weight: 0.33kg, y = 1.70kg, z =0.25kg


#### 연속된 정수 데이터의 작성

In [7]:
y = range(5,10)
print(y[0],y[1],y[2],y[3],y[4])

5 6 7 8 9


In [8]:
print(y)

range(5, 10)


In [9]:
#수정 불가
y[2] = 2

TypeError: 'range' object does not support item assignment

In [10]:
z = list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


In [11]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### tuple

In [12]:
a= (1,2,3)
print(a)

(1, 2, 3)


#### 요소의 참조

In [13]:
a[1]

2

In [14]:
type(a)

tuple

In [15]:
type(a[1])

int

In [16]:
a = (1)

In [17]:
type(a)

int

In [18]:
#길이가 1인 튜플
a = (1,)

In [19]:
type(a)

tuple

In [20]:
print(a)

(1,)


#### if문

In [21]:
x = 11
if x>10:
    print("x is ")
    print("      larger than 10.")
else:
    print("x is smaller than 11")

x is 
      larger than 10.


In [22]:
type(x>10)

bool

#### enumerate의 이용

In [24]:
num = [2,4,6,8,10]
for i, n in enumerate(num):
    num[i] = n*2
print(num)

[4, 8, 12, 16, 20]


#### 벡터

In [25]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [26]:
import numpy as np

#### 벡터의 정의

In [27]:
x = np.array([1,2,3])
x


array([1, 2, 3])

In [28]:
print(x)

[1 2 3]


In [30]:
y = np.array([4,5,6])
print(x+y)

[5 7 9]


In [31]:
type(x)

numpy.ndarray

In [32]:
x[0]

1

In [33]:
x[0] = 100
print(x)

[100   2   3]


In [34]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


#### ndarray 형의 주의점
<br>복사하려면 b = a 가 아닌 b = a.copy()를 사용해야 함

b = a 사용시:

In [37]:
a= np.array([1,1])
b = a
print("a = "+str(a))
print("b = "+str(b))
b[0] = 100#a까지 바뀌어버림
print('b = '+str(b))
print('a = '+str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [100   1]


b = a.copy() 사용시:

In [38]:
a = np.array([1,1])
b = a.copy()
print("a ="+str(a))
print("b ="+str(b))
b[0]= 100
print("b = "+str(b))
print("a = "+str(a))

a =[1 1]
b =[1 1]
b = [100   1]
a = [1 1]


### 행렬

In [39]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [40]:
x.shape

(2, 3)

In [41]:
w, h = x.shape
print(w)
print(h)

2
3


In [42]:
x = np.array([[1,2,3],[4,5,6]])
x[1,2]

6

In [43]:
x[1][2]

6

In [44]:
x[0,2]

3

In [45]:
x[0][2]

3

In [46]:
#요소의 수정
x[1,2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [47]:
x[1][2] = 38
print(x)

[[ 1  2  3]
 [ 4  5 38]]


In [48]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [49]:
print(np.zeros_like(10))

0


In [51]:
print(np.ones((2,19)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [52]:
np.random.rand(2,3)

array([[0.99676193, 0.83926912, 0.37099714],
       [0.91686459, 0.41977984, 0.84896602]])

### 행렬의 크기 변경

In [54]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 스칼라 x 행렬

In [56]:
x = np.array([[4,4,4],[8,8,8]])
print(10*x)

[[40 40 40]
 [80 80 80]]


In [57]:
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


#### 행렬 곱

In [58]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])

print(v.dot(w))

[[14 14]
 [32 32]]


In [60]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [61]:
print(x[5:])

[5 6 7 8 9]


In [62]:
print(x[3:8])

[3 4 5 6 7]


In [63]:
print(x[3:8:2])

[3 5 7]


In [65]:
#배열 순서 반대로
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [69]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print('\n')
print(y[:2,1:2])
print('\n')
print(y[:2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[2]
 [5]]


[[2 3]
 [5 6]]


#### bool 배열 사용

In [70]:
x = np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [71]:
x[x>3]

array([ 5,  8, 13])

In [72]:
x[x>3] = 999
x

array([  1,   1,   2,   3, 999, 999, 999])

#### help 사용

In [73]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [74]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

#### 함수

In [75]:
def my_func1():
    print("Hi!")

my_func1()

Hi!


In [76]:
def my_func2(a,b):
    c = a + b
    return c

my_func2(1,4)

5

In [77]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m,s

In [79]:
data = np.random.randn(100)
data[:3]
data.max()

2.2933445774364825

In [80]:
data_mean, data_std = my_func3(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean,data_std))

mean:-0.25, std:1.06


In [81]:
output = my_func3(data)
print(output)
print(type(output))
print("mean:{0:3.2f}, std:{1:3.2f}".format(output[0],output[1]))

(-0.24653054113803638, 1.0599564459851734)
<class 'tuple'>
mean:-0.25, std:1.06


### 파일 저장

In [82]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy',data)
data =[]#데이터 삭제
print(data)
data = np.load('datafile.npy')
print(data)

[-0.38213681 -2.15013954  1.25291361  2.81152004 -0.32170748]
[]
[-0.38213681 -2.15013954  1.25291361  2.81152004 -0.32170748]


### 여러 ndarray 형을 저장

In [83]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz',data1 = data1, data2=data2)#세이브
data1 = []
data2 = []
outfile = np.load('datafile2.npz')
print(outfile.files)

['data1', 'data2']


In [2]:
import numpy as np
data = np.array(['채은아','사랑해','하나님','죄송해요'])
np.savez('ily.npz',data)


In [84]:
print(outfile)

In [85]:
data1 = outfile['data1']
data2 = outfile['data2']

print(data1)
print(data2)

[1 2 3]
[10 20 30]
